- client/src/pages/HomePage/HomePage.tsx
- client/src/pages/RegisterPage/RegisterPage.tsx
Motivation :
eslint 로 인한 client 코드 warning 으로 인해 github action build 동작이 수행되지 않는다.
Modifications:
- eslint warning 요소들을 제거했다.
Result:
로컬 환경에서 eslint 이슈 없이 잘 build 가 되는지 확인했다. 
close #20
> [hotfix/github_action_build_error] eslint 에러 요소 제거

- .github/workflows/deploy.yml
- client/Dockerfile
- client/default.conf
- docker-compose-build.yml
- docker-compose.yml
- nginx/Dockerfile
- nginx/default.conf
- server/Dockerfile
- server/src/main.ts
Motivation :
- 시스템 구성도에 따라 컨테이너를 구성한다
- github action과 docker를 이용해 cd를 구축한다.
Modifications:
- `client`, `server`, `nginx` 폴더마다 dockerfile 구성 및 docker-compose 설정 파일 구성
- github action 배포 스크립트 작성
Result:
- `dev` 브랜치에 push 시 github action에서 빌드 후 배포
- github packages에 이미지 저장
- close #12
> [ci/cd] docker 설정 및 github action 스크립트 작성

- .github/workflows/ci.yml
Motivation :
- PR시에 빌드 검사를 통해 eslint 검사 및 빌드 테스트를한다.
Modifications:
- github action ci 파일추가
Result:
- `dev` 브랜치에 prtl build 검사시작
- close #12
> [ci] PR시 build 테스트

- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
- server/src/cache/cache.module.ts
- server/src/database/database.provider.ts
- server/src/main.ts
- server/src/redis.ts
회원가입 이후, 로그인 시 요청에 대한 응답이 대기 상태로 묶여있던 현상이 발견되었다.
- Redis와 관련된 모듈 분리
- Session과 Redis 수동 연결 (connectRedis 사용 X)
- Redis에 { key: session.id, value: userEmail } 정보 저장
회원가입 이후, 로그인시 세션에 회원 이메일 정보와 로그인 상태를 저장하고 홈 화면으로 이동한다.
close #5 #7
> [be/bugfix pending login] 로그인 요청시 대기 상태 문제

- .github/workflows/deploy.yml
- server/.gitignore
- server/src/main.ts
Motivation :
- 배포서버에 env 파일이 누락되었다.
Modifications:
- CD 로직에 secret 을 통해 env파일 추가
Result:
- 배포서버에서 env 파일을 사용가능
> [cd/server-env] 배포서버에 서버 env 파일 추가

- server/package-lock.json
- server/package.json
- server/src/S3/S3.module.ts
- server/src/S3/s3.service.spec.ts
- server/src/S3/s3.service.ts
- server/src/app.module.ts
- server/src/user/dto/check-name.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.repository.ts
- server/src/user/user.service.ts
Motivation :
- 오브젝트 스토리지 이미지 저장
- 오브젝트 스토리지에 이미지를 저장하는 태스크를 프론트엔드에서 백엔드로 옮김. (이미지 크기 조절 및 유저 인가 등을 서버에서 처리할 수 있도록 하기 위해)
- 차후  S3 module(S3 service)의 uploadFiles()를 호출해 Express.Multer.File 타입의 이미지 파일(`@UseInterceptors(FileInterceptor())` 및 `@UploadedFiles()`를 사용해 받을 수 있음)을 오브젝트 스토리지로 저장할 수 있음.
- 별명 중복 체크 기능
- 유저 회원가입 및 별명 수정 시 중복되는 이름이 없도록 중복 체크를 해주는 api를 만들기로 함.
Modifications:
- 오브젝트 스토리지 이미지 저장 모듈 구현(S3 module)
- 별명 중복 체크 api 구현(api/user/nameCheck)
Result:
- 오브젝트 스토리지에 이미지가 .jpg 파일로 업로드됨.
- DB에 존재하는 별명에 대해 isExist를 true로 반환.
close #38 #49
> [ be/common] 오브젝트 스토리지 이미지 저장 & 별명 중복 체크 기능 구현

- client/src/apis/api/BoardApi.ts
- client/src/apis/api/commentApi.ts
- client/src/apis/api/loginApi.ts
- client/src/apis/api/newPostApi.ts
- client/src/apis/config.ts
- client/src/pages/CommentPage/CommentPage.tsx
- client/src/pages/LoadingPage/LoadingPage.tsx
- client/src/pages/NewPostPage/NewPostPage.tsx
- client/src/pages/RegisterPage/RegisterPage.tsx
- client/src/types/responseData.ts
Motivation: 
- api 명세 변경에 따른 내부 로직 수정
Modifications:
- api 경로 수정
- form data 전송 부분 변경
- response type 변경 및 이로 인한 에러 수정
Result: 
- Mock server 테스트 완료
- 빌드 및 lint, prettier 체크 완료
> [fe/refactor_api] api 명세 변경에 따른 코드 수정

- client/default.conf
- 배포서버 404 에러를 해결
- client 쪽 nginx 설정 수정
- github api secret 수정
- 로컬환경과 동일하게 돌아가게 되었다
> [bug/deploy-error] 배포 에러 수정

- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/auth/auth.guard.ts
- server/src/auth/auth.service.ts
- server/src/board/board.controller.ts
- server/src/main.ts
- 로그인한 유저만 api 요청을 할 수 있게 한다.
- useguard를 이용해 유저의 세션이 레디스에 있는지 검증한다.
- 로그인을 위한 auth api 이외의 api 요청에는
`{
"statusCode": 403,
"message": "Forbidden resource",
"error": "Forbidden"
}`
응답을 반환한다.
- close #34
> [be/authrozation] 로그인 인가 

- client/src/apis/api/BoardApi.ts
- client/src/apis/api/commentApi.ts
- client/src/apis/api/loginApi.ts
- client/src/apis/api/newPostApi.ts
- client/src/components/BoardItem/BoardBody/BoardBodyStyles.tsx
- client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
- client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
- client/src/components/BoardItem/BoardItem.tsx
- client/src/pages/CommentPage/CommentPage.tsx
- client/src/pages/HomePage/HomePage.tsx
- client/src/pages/LoadingPage/LoadingPage.tsx
- client/src/store/userAtom.ts
- client/src/types/responseData.ts
- server/src/S3/S3.service.ts
- server/src/app.module.ts
- server/src/auth/auth.service.ts
- server/src/board/board.controller.ts
- server/src/board/board.entity.ts
- server/src/board/board.repository.ts
- server/src/board/board.service.ts
- server/src/board/dto/createBoardDto.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.entity.ts
- server/src/comment/comment.repository.ts
- server/src/configs/typeorm.config.ts
- 배포 시 💥무수한💥 버그가 있다. 
- 게시글 로딩 이슈 해결
- s3 이미지 업로드시 content-type 설정 변경
- api 명세 수정
- 오타 수정
- 게시글 등록시 multipart/form data 처리
- 
- 배포시 어플리케이션이 잘 작동한다
> [be/deploy-bugfix] 배포시 버그 수정

- server/src/board/board.controller.ts
- server/src/board/board.module.ts
- server/src/board/board.repository.ts
- server/src/board/board.service.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.entity.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.repository.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/create-comment.dto.ts
- server/src/comment/dto/delete-comment.dto.ts
- server/src/comment/dto/update-comment.dto.ts
Motivation :
- 댓글을 수정하거나 삭제할 수 있음
- 댓글 작성자 본인이 아닌 경우 댓글을 수정할 수 없음
- 댓글 작성자 본인이거나 게시글 작성자 본인이 아닌 경우 댓글을 삭제할 수 없음
- 게시글 작성자 본인이 아닌 경우 게시글을 수정하거나 삭제할 수 없음
Modifications:
- 댓글 수정 API 작성
- 댓글 삭제 API 작성
- 게시글 수정,삭제 Exception 처리
Result:
댓글을 수정하거나 삭제할 수 있다.
단, 작성자 본인이 아닌 경우 예외가 발생한다.
close #53 #91
> [be/comment] 댓글 수정, 삭제 API 구현

- .github/workflows/deploy.yml
Motivation :
- cd 경로에 오류가 있다.
Modifications:
- env 파일 복사 경로 수정
Result:
- 버그수정
> [be/https] 경로수정

- .github/workflows/deploy.yml
- environment/docker-compose-build.yml
Motivation :
- deploy working directory 변경으로 docker compose 경로 오류 에러가난다.
Modifications:
- docker-compose 경로변경
Result:
- 배포 정상화
> [be/https] 경로변경 적용

- environment/default.conf
- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/auth/auth.guard.ts
- server/src/board/board.entity.ts
- server/src/board/board.repository.ts
- server/src/board/board.service.ts
- server/src/board/board.util.ts
- server/src/board/photo.entity.ts
- server/src/configs/typeorm.config.ts
- server/src/map/dto/get-map.dto.ts
- server/src/map/map.controller.spec.ts
- server/src/map/map.controller.ts
- server/src/map/map.module.ts
- server/src/map/map.service.spec.ts
- server/src/map/map.service.ts
- 게시판의 정보를 위도와 경도 기준으로 불러올 필요가 있다.
- board 테이블의 위치정보를 geometry 타입으로 변경
- x,y 값이 제일 작은 좌표와 제일 큰 좌표의 사각형안에 위치정보가 있는 게시물들을 모두 불러온다
- geometry 데이터 타입으로 빠른 위치데이터 조회가 가능해졌다
close #80
> [be/map] map api 작성

- client/src/pages/MapPage/MapPage.tsx
Motivation :
- 검색된 데이터가 없을 경우에 대해 처리
Modifications:
- POST의 경우, 응답으로 statusCode: 201을 전송하는 것으로 변경하여 적용
- 검색된 데이터가 없는 경우, 게시글 정보를 페이지에 업데이트하지 않도록 하여 요청 및 렌더링이 일어나지 않도록 하였다.
Result:
- 서버와 Map API를 통하여 원활한 통신이 가능해졌다.
- 더이상 에러가 발생하지 않는다.
> [fe/map] 지도 페이지 API 명세 변경사항 적용 및 검색된 데이터가 없는 경우 처리

- client/src/apis/api/boardApi.ts
- client/src/apis/api/userApi.ts
- client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
- client/src/components/UserInfoContainer/UserInfoContainer.tsx
- client/src/pages/ModifyPage/ModifyPage.tsx
- server/src/board/board.service.ts
- server/src/user/dto/get-profile-info.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
Motivation :
버그 수정 및 이벤트 추가 등 리팩토링
Modifications:
- 개인페이지 정보 조회 api 수정
- viewerId request query string에 추가
- followed_by, followed_by_viewr 정보 응답()
- 계정명 클릭시 개인페이지로 이동
- 게시글 수정 확인 클릭 이벤트 추가
- 게시글 삭제시 페이지 리로드
Result:
버그 해결
> [be/refactor] bug fix

- client/src/apis/api/reverseGeocoding.ts
- client/src/apis/services/reverseGeocodingService.ts
- client/src/setupProxy.js
- server/src/board/board.repository.ts
- server/src/map/map.controller.ts
- server/src/map/map.module.ts
- server/src/map/map.service.ts
- 배포서버에서 새 글 작성시 작성자의 현재 위치가 조회되지 않았다.
- 네이버지도로의 요청을 서버에서 보낼 필요를 확인함
- client에 env 있던 네이버 지도 관련 정보를 서버로 변경
- 기존의 `client-> 네이버 지도`로 보내던 요청을 `client -> server -> 네이버 지도` 로 우회함
- 사용자 위치를 불러올 수 있다.
> [bug/map]현재 위치 조회 api 수정

- client/src/apis/api/boardApi.ts
- client/src/components/BoardItem/BoardBody/BoardBody.tsx
- client/src/components/BoardItem/BoardBody/BoardBodyStyles.tsx
- client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
- client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
- client/src/components/BoardItem/BoardItem.tsx
- client/src/components/BoardModal/BoardModal.tsx
- client/src/components/BoardModal/BoardModalStyles.tsx
- client/src/components/ImageCarousel/ImageCarousel.tsx
- client/src/components/LikeButton/LikeButton.tsx
- client/src/pages/HomePage/HomePage.tsx
- client/src/pages/HomePage/HomePageStyles.tsx
- client/src/store/boardDetailAtom.ts
- client/src/types/responseData.ts
- server/src/like/like.repository.ts
- 인스타그램과 같이, 사용자가 마음에드는 게시글에 좋아요를 표시하는 기능을 제공
- 게시글의 좋아요 버튼 클릭시 서버에 API 요청으로 좋아요한 사용자로 등록
- 다시 누르는 경우, 좋아요가 취소되며 API 요청을 통해 사용자 등록을 삭제
- 응답으로 오는 likeCount를 이용하여 front에서 좋아요 수 정보를 업데이트
- 사용자가 마음에 드는 게시글에 좋아요를 표시할 수 있다.
close #125
> [fe/like] 좋아요 기능 구현

- server/src/auth/auth.guard.ts
- server/src/auth/auth.service.ts
- server/src/board/board.controller.ts
- server/src/board/board.repository.ts
- server/src/board/board.service.ts
- server/src/map/map.controller.ts
- server/src/map/map.service.ts
- 로그인중인 유저의 게시글 좋아요 여부 확인이 필요하다
- 로그인시 세션쿠키에 유저 ID저장
- db조회 하면서 좋아요 여부 확인
- 좋아요 여부를 isLiked 를 통해 확인할 수있다.
close #115
> [be/like enhanced] 게시글 불러오기시 좋아요 여부 확인

- client/src/apis/api/mapApi.ts
- client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
- client/src/pages/HomePage/HomePage.tsx
- client/src/pages/MapPage/MapPage.tsx
- client/src/types/responseData.ts
- client/src/utils/map/map.ts
- client/src/utils/map/naverMap.ts
- useEffect와 useState로 복잡한 코드로 읽기 힘들어 정리가 필요하다고 느꼈다.
- useEffect + useState + API 요청 대신 React Query를 사용하여 코드를 간소화하였다.
- 서버로부터 데이터를 받아오는 로직의 코드를 줄이고, 가독성을 향상시켰다.
> [fe/apply react query] 게시글 및 지도 관련 API React Query 적용

- server/src/board/board.entity.ts
- server/src/board/board.repository.ts
- server/src/like/like.repository.ts
- server/src/like/like.service.ts
- 게시물의 좋아요 여부를 제대로 표시못하는 버그가 있었다.
- 관련 버그수정
- 게시물 불러오는 모든 레포지토리 코드에 적용
- 버그해결
close #issueNum
> [be/like-enhanced] 좋아요 api 버그수정

- client/src/components/SetLocationModal/SetLocationModalStyles.tsx
- client/src/pages/NewPostPage/NewPostPage.tsx
- client/src/utils/map/naverMap.ts
- 모바일 지도 잘림 현상 발생
- 지도 크기 스타일 vw, vh 대신 % 사용 및 크기 수정
- 지도 크기 수정
> [fe/map update] 모바일 버그 수정
